/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:472ffbdc-c6ff-48e3-844a-80ecb9899ff1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yxUEKLi7L",
    "aws_user_pools_web_client_id": "4fv3q2mdsshtp9geittvc6bdva",
    "oauth": {}
};


export default awsmobile;
